---
title: "R Notebook"
output: html_notebook
---

# Review Regresi
```{r}
beta0 = 0
beta1 = 0
dataX = c(1:20)
err = 5*rnorm(length(dataX))
dataY = beta0 + beta1*dataX + err
df = data.frame(X=dataX, Y=dataY)
df
```

```{r}
plot(df)
```
```{r}
model = lm(Y ~ X, df)
summary(model)
```
```{r}
b0 = model$coefficients[1]
b1 = model$coefficients[2]
titikX = c(df$X[1], df$X[length(df$X)])
titikY = b0 + b1*titikX

library(ggplot2)
ggplot() + 
  geom_line(aes(titikX, titikY)) +  
  geom_point(aes(df$X, df$Y))
```

# Analisis Korelasi

## Korelasi Pearson
```{r}
DataRegresi = data.frame(Y=c(35,49,27,33,60,21,45),
                         X=c(8,9,7,6,13,7,11))
DataRegresi
```
```{r}
plot(DataRegresi$X, DataRegresi$Y)
```

```{r}
cor.test(DataRegresi$Y, DataRegresi$X, alternative="g", method=c("p"))
```
```{r}
DataKinerja = data.frame(Kepuasan=c(1,1,3,4,2,2,3,4,3,4),
                         Kinerja=c(1,2,3,3,1,3,4,4,3,4))
DataKinerja
```
```{r}
plot(DataKinerja$Kepuasan,DataKinerja$Kinerja, ylim=c(0,5), xlim=c(0,5), main="Plot antara Kepuasan dan Kinerja")
```
```{r}
cor.test(DataKinerja$Kepuasan, DataKinerja$Kinerja, alternative="t", method=c("s"),exact=FALSE)
```



## Kendall's Tau
```{r}
cor.test(DataKinerja$Kepuasan, DataKinerja$Kinerja, alternative="t", method=c("k"),exact=FALSE)
```

```{r}
Rusak = c(4,7,6,6,5,1,3,5,3,4,8,6,8,9,5)
Mesin = c("1", "1", "1", "1", "2", "2", "2", "2", "2", "2","3", "3", "3", "3", "3")
length(Rusak) == length(Mesin)

```
```{r}
fit = lm(Rusak~Mesin)
fit
```
```{r}
summary(fit)
```

```{r}
anova(fit)
```




